version: "3.9"

services:
  redis:
    image: redis/redis-stack:latest      # includes RedisJSON / Search
    ports:
      - "6379:6379"

  api:
    build: ./app/api
    environment:
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
    ports:
      - "8080:8080"

  web:
    build: ./app/web
    environment:
      NEXT_PUBLIC_API_BASE: "/api"        # calls proxy rewrite
    depends_on:
      - api
    ports:
      - "3000:3000"